// Content Safety Blocklist for COPPA Compliance (US-014)
// 200+ terms organized by category for child-safe content filtering.
// Used by contentSafetyService.ts for both user input and AI output checks.

export interface BlocklistCategory {
  name: string;
  terms: string[];
}

// Friendly message shown when content is blocked (non-shaming per design guidelines)
export const CONTENT_BLOCKED_USER_MESSAGE =
  "Let's try a different direction for our story!";

export const CONTENT_BLOCKED_OUTPUT_MESSAGE =
  "Hmm, that part of the story didn't work out. Let's take the story in a new direction!";

export const BLOCKLIST_CATEGORIES: BlocklistCategory[] = [
  {
    name: 'violence',
    terms: [
      'murder',
      'kill',
      'killing',
      'stab',
      'stabbing',
      'shoot',
      'shooting',
      'slaughter',
      'massacre',
      'assassinate',
      'assassination',
      'execute',
      'execution',
      'behead',
      'beheading',
      'decapitate',
      'dismember',
      'mutilate',
      'mutilation',
      'torture',
      'torment',
      'strangle',
      'strangling',
      'suffocate',
      'drown',
      'drowning',
      'bloodbath',
      'bloodshed',
      'carnage',
      'gore',
      'gory',
      'disembowel',
      'eviscerate',
      'maim',
      'manslaughter',
      'homicide',
      'genocide',
      'infanticide',
      'sniper',
      'gunshot',
      'headshot',
      'lethal',
      'machete',
    ],
  },
  {
    name: 'weapons',
    terms: [
      'gun',
      'rifle',
      'pistol',
      'shotgun',
      'revolver',
      'firearm',
      'ammunition',
      'ammo',
      'grenade',
      'explosive',
      'dynamite',
      'bomb',
      'bombing',
      'landmine',
      'missile',
      'rocket launcher',
      'ak-47',
      'ar-15',
      'uzi',
      'assault rifle',
      'semiautomatic',
      'automatic weapon',
      'switchblade',
      'brass knuckles',
      'nunchucks',
      'flamethrower',
      'molotov cocktail',
      'silencer',
      'suppressor',
    ],
  },
  {
    name: 'sexual_content',
    terms: [
      'sex',
      'sexual',
      'sexually',
      'intercourse',
      'orgasm',
      'erotic',
      'erotica',
      'pornography',
      'porn',
      'pornographic',
      'nude',
      'nudity',
      'naked',
      'genitals',
      'genital',
      'penis',
      'vagina',
      'breasts',
      'masturbate',
      'masturbation',
      'fetish',
      'bondage',
      'bdsm',
      'strip club',
      'stripper',
      'prostitute',
      'prostitution',
      'hooker',
      'escort service',
      'brothel',
      'sexually explicit',
      'seduce',
      'seduction',
      'foreplay',
      'aphrodisiac',
      'orgy',
      'threesome',
      'voyeur',
      'voyeurism',
      'exhibitionist',
      'grope',
      'groping',
      'molest',
      'molestation',
      'pedophile',
      'pedophilia',
      'rape',
      'rapist',
      'sexual assault',
      'sexual abuse',
      'incest',
    ],
  },
  {
    name: 'self_harm',
    terms: [
      'suicide',
      'suicidal',
      'self-harm',
      'self harm',
      'cutting myself',
      'cut myself',
      'kill myself',
      'hang myself',
      'overdose',
      'slit wrists',
      'slit my wrists',
      'jump off',
      'end my life',
      'end it all',
      'want to die',
      'wanna die',
      'noose',
      'self-mutilation',
      'self mutilation',
      'anorexia',
      'anorexic',
      'bulimia',
      'bulimic',
      'purging',
      'starve myself',
      'pro-ana',
      'pro-mia',
      'thinspo',
    ],
  },
  {
    name: 'substance_abuse',
    terms: [
      'cocaine',
      'heroin',
      'methamphetamine',
      'meth',
      'crack',
      'crack cocaine',
      'ecstasy',
      'mdma',
      'lsd',
      'acid trip',
      'shrooms',
      'magic mushrooms',
      'pcp',
      'ketamine',
      'fentanyl',
      'opioid',
      'opiate',
      'morphine',
      'codeine',
      'oxycodone',
      'oxycontin',
      'hydrocodone',
      'vicodin',
      'percocet',
      'xanax',
      'valium',
      'adderall',
      'ritalin',
      'amphetamine',
      'barbiturate',
      'drug dealer',
      'drug dealing',
      'drug trafficking',
      'drug abuse',
      'drug addict',
      'substance abuse',
      'getting high',
      'snort',
      'snorting',
      'inject drugs',
      'shooting up',
      'smoke weed',
      'marijuana',
      'cannabis',
      'edibles',
      'vaping',
      'vape',
      'juul',
      'nicotine',
      'cigarette',
      'tobacco',
      'drunk',
      'drunken',
      'alcoholic',
      'alcohol abuse',
      'binge drinking',
      'moonshine',
      'bootleg',
    ],
  },
  {
    name: 'profanity',
    terms: [
      'fuck',
      'fucking',
      'fucker',
      'motherfucker',
      'shit',
      'shitty',
      'bullshit',
      'ass',
      'asshole',
      'bitch',
      'bitchy',
      'bastard',
      'damn',
      'damned',
      'damnit',
      'goddamn',
      'goddamnit',
      'hell',
      'crap',
      'piss',
      'pissed',
      'dick',
      'dickhead',
      'cock',
      'cunt',
      'twat',
      'whore',
      'slut',
      'skank',
      'douche',
      'douchebag',
      'jackass',
      'wanker',
      'bollocks',
      'arse',
      'arsehole',
      'bloody hell',
      'bugger',
      'tosser',
      'prick',
    ],
  },
  {
    name: 'hate_speech',
    terms: [
      'nigger',
      'nigga',
      'kike',
      'spic',
      'wetback',
      'chink',
      'gook',
      'jap',
      'raghead',
      'towelhead',
      'camel jockey',
      'beaner',
      'gringo',
      'cracker',
      'honky',
      'redneck',
      'white trash',
      'white supremacy',
      'white supremacist',
      'neo-nazi',
      'nazi',
      'aryan',
      'aryan nation',
      'kkk',
      'ku klux klan',
      'master race',
      'ethnic cleansing',
      'race war',
      'racial purity',
      'heil hitler',
      'sieg heil',
      'jihad',
      'jihadist',
      'infidel',
      'crusade',
      'homophobe',
      'homophobia',
      'faggot',
      'fag',
      'dyke',
      'tranny',
      'transphobe',
      'transphobia',
      'retard',
      'retarded',
      'cripple',
    ],
  },
  {
    name: 'age_inappropriate',
    terms: [
      'gambling',
      'casino',
      'slot machine',
      'poker game',
      'blackjack',
      'roulette',
      'betting',
      'wager',
      'serial killer',
      'mass shooting',
      'school shooting',
      'terrorist',
      'terrorism',
      'hostage',
      'kidnap',
      'kidnapping',
      'human trafficking',
      'slave trade',
      'slavery',
      'child labor',
      'child labour',
      'sweatshop',
      'death penalty',
      'electric chair',
      'lethal injection',
      'gas chamber',
      'concentration camp',
      'holocaust',
      'war crime',
      'war crimes',
      'crime scene',
      'dead body',
      'corpse',
      'cadaver',
      'autopsy',
      'domestic violence',
      'child abuse',
      'spousal abuse',
      'gang violence',
      'gang war',
      'drive-by',
      'black market',
      'money laundering',
      'extortion',
      'loan shark',
      'hitman',
      'contract killer',
    ],
  },
];

// Pre-compiled flat list and regex map for performance
let _flatTerms: string[] | null = null;
let _regexMap: Map<string, RegExp> | null = null;

/**
 * Returns a flat array of all blocklist terms across all categories.
 * Cached after first call.
 */
export function getAllBlocklistTerms(): string[] {
  if (!_flatTerms) {
    _flatTerms = BLOCKLIST_CATEGORIES.flatMap(cat => cat.terms);
  }
  return _flatTerms;
}

/**
 * Returns a map of term -> pre-compiled word-boundary regex.
 * Cached after first call for performance.
 */
export function getBlocklistRegexMap(): Map<string, RegExp> {
  if (!_regexMap) {
    _regexMap = new Map();
    for (const category of BLOCKLIST_CATEGORIES) {
      for (const term of category.terms) {
        // Multi-word terms get escaped; single words use \b word boundary
        const escaped = term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        _regexMap.set(term, new RegExp(`\\b${escaped}\\b`, 'i'));
      }
    }
  }
  return _regexMap;
}

/**
 * Returns the total number of unique terms in the blocklist.
 */
export function getBlocklistTermCount(): number {
  return getAllBlocklistTerms().length;
}

/**
 * Returns category names that contain a matched term.
 */
export function getCategoriesForTerm(term: string): string[] {
  const lowerTerm = term.toLowerCase();
  return BLOCKLIST_CATEGORIES.filter(cat =>
    cat.terms.some(t => t.toLowerCase() === lowerTerm),
  ).map(cat => cat.name);
}
