-- Verification Script for story-images Bucket Setup
-- Run this script to verify the bucket and RLS policies are correctly configured

-- ============================================================================
-- Test 1: Verify bucket exists and is private
-- ============================================================================
SELECT
  '✅ Test 1: Verify bucket exists and is private' as test_name;

SELECT
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types,
  created_at
FROM storage.buckets
WHERE id = 'story-images';

-- Expected Result:
-- id: story-images
-- name: story-images
-- public: false
-- file_size_limit: 10485760
-- created_at: (timestamp)

-- ============================================================================
-- Test 2: Verify all RLS policies exist
-- ============================================================================
SELECT
  '✅ Test 2: Verify all RLS policies exist (expecting 4 rows)' as test_name;

SELECT
  policyname,
  cmd,
  qual,
  with_check
FROM pg_policies
WHERE tablename = 'objects'
  AND schemaname = 'storage'
  AND policyname LIKE 'story-images%'
ORDER BY cmd;

-- Expected Result: 4 rows (one for each command: DELETE, INSERT, SELECT, UPDATE)
-- Policy names may be auto-generated by Supabase Dashboard

-- ============================================================================
-- Test 3: Verify RLS is enabled on storage.objects
-- ============================================================================
SELECT
  '✅ Test 3: Verify RLS is enabled (expecting rowsecurity=true)' as test_name;

SELECT
  schemaname,
  tablename,
  rowsecurity
FROM pg_tables
WHERE schemaname = 'storage'
  AND tablename = 'objects';

-- Expected Result:
-- rowsecurity: true

-- ============================================================================
-- Test 4: Verify policy definitions contain correct bucket filter
-- ============================================================================
SELECT
  '✅ Test 4: Verify bucket filter in policies' as test_name;

SELECT
  policyname,
  cmd,
  CASE
    WHEN qual LIKE '%story-images%' OR with_check LIKE '%story-images%' THEN 'Contains bucket filter'
    ELSE 'MISSING bucket filter'
  END as bucket_filter_status
FROM pg_policies
WHERE tablename = 'objects'
  AND schemaname = 'storage'
  AND policyname LIKE 'story-images%';

-- Expected Result: All rows should show "Contains bucket filter"

-- ============================================================================
-- Test 5: Verify policy definitions check user folder ownership
-- ============================================================================
SELECT
  '✅ Test 5: Verify user ownership checks in policies' as test_name;

SELECT
  policyname,
  cmd,
  CASE
    WHEN qual LIKE '%auth.uid()%' OR with_check LIKE '%auth.uid()%' THEN 'Checks user ownership'
    ELSE 'MISSING ownership check'
  END as ownership_check_status
FROM pg_policies
WHERE tablename = 'objects'
  AND schemaname = 'storage'
  AND policyname LIKE 'story-images%';

-- Expected Result: All rows should show "Checks user ownership"

-- ============================================================================
-- Summary Report
-- ============================================================================
SELECT
  'story-images Storage Bucket Verification' as report_title,
  CASE
    WHEN (SELECT COUNT(*) FROM storage.buckets WHERE id = 'story-images') = 1
    THEN '✅ PASS'
    ELSE '❌ FAIL'
  END as bucket_exists,
  CASE
    WHEN (SELECT public FROM storage.buckets WHERE id = 'story-images') = false
    THEN '✅ PASS (private)'
    ELSE '❌ FAIL (should be private)'
  END as bucket_privacy,
  CASE
    WHEN (SELECT COUNT(*) FROM pg_policies
          WHERE tablename = 'objects'
          AND schemaname = 'storage'
          AND policyname LIKE 'story-images%') = 4
    THEN '✅ PASS (4 policies)'
    ELSE CONCAT('❌ FAIL (found ',
                (SELECT COUNT(*) FROM pg_policies
                 WHERE tablename = 'objects'
                 AND schemaname = 'storage'
                 AND policyname LIKE 'story-images%')::text,
                ' policies, expected 4)')
  END as rls_policies,
  CASE
    WHEN (SELECT rowsecurity FROM pg_tables WHERE schemaname = 'storage' AND tablename = 'objects') = true
    THEN '✅ PASS'
    ELSE '❌ FAIL'
  END as rls_enabled;

-- ============================================================================
-- Cleanup (Optional - only run if you need to recreate the bucket)
-- ============================================================================
-- WARNING: This will delete ALL policies for story-images and the bucket itself!
-- UNCOMMENT AND RUN THE FOLLOWING TO DELETE:

/*
DO $$
DECLARE
  policy_record RECORD;
BEGIN
  -- Drop all policies for story-images bucket
  FOR policy_record IN
    SELECT policyname
    FROM pg_policies
    WHERE tablename = 'objects'
      AND schemaname = 'storage'
      AND policyname LIKE 'story-images%'
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON storage.objects', policy_record.policyname);
  END LOOP;
END $$;

-- Delete the bucket
DELETE FROM storage.buckets WHERE id = 'story-images';
*/
